name: jiwaapp_task7
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dotted_line: ^3.2.3
  url_launcher: ^6.3.1
  geolocator: ^14.0.0
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/logo/
    - assets/banner/
